/** Stabil E2E szelektorok — elsősorban data-testid, másképp role/ID. */

export const sel = {
  storefront: "[data-testid=storefront]",
  authWidget: "[data-testid=auth-widget]",
  authLoggedOut: "[data-testid=auth-logged-out]",
  authLoggedIn: "[data-testid=auth-logged-in]",
  loginForm: "[data-testid=login-form]",
  loginEmail: "#loginEmail",
  loginPassword: "#loginPassword",
  logoutBtn: "#logoutBtn",
  cartFab: "[data-testid=cart-fab]",
  adminFab: "[data-testid=admin-fab]",
  sideNav: "[data-testid=side-nav]",
  navWebshop: '[data-testid=side-nav] button[data-view="webshop"]',
  navGallery: '[data-testid=side-nav] button[data-view="gallery"]',
  navStories: '[data-testid=side-nav] button[data-view="stories"]',
  navStorybooks: '[data-testid=side-nav] button[data-view="storybooks"]',
  navCart: '[data-testid=side-nav] button[data-view="cart"]',
  viewWebshop: "[data-testid=view-webshop]",
  viewGallery: "[data-testid=view-gallery]",
  viewCart: "[data-testid=view-cart]",
  viewStorybooks: "[data-testid=view-storybooks]",
  productsOut: "#productsOut",
  productsCatalogOut: "#productsCatalogOut",
  galleryPublicOut: "#galleryPublicOut",
  heroGlass: "#heroGlass",
  adminLoginForm: "[data-testid=admin-login-form]",
  adminUsername: "#username",
  adminPassword: "#password",
  adminApp: "[data-testid=admin-app]",
  adminTopnav: "[data-testid=admin-topnav]",
  adminDashboard: "[data-testid=admin-dashboard]",
  adminNews: "[data-testid=admin-news]",
  adminNavOrders: '[data-testid=admin-topnav] button[data-nav="orders"]',
  adminNavGallery: '[data-testid=admin-topnav] button[data-nav="gallery"]',
  adminNavStorybooks: '[data-testid=admin-topnav] button[data-nav="storybooks"]',
} as const;
